#!/bin/bash

# Make sure we fail and exit on the command that actually failed.
set -e
set -o pipefail

# Previously was building using lein
#lein run -m clojure.main script/build.clj

# Build our own copy of ClojureScript compiler
CLJS_GIT_COMMIT=4681e47418ead29156ca01d58eee700e11c1e096
if [ ! -e clojurescript ]; then
   git clone https://github.com/clojure/clojurescript
   pushd clojurescript
   git reset --hard $CLJS_GIT_COMMIT
   # Apply patches
   curl -L https://github.com/darwin/clojurescript/commit/e32260c42db821d593d112ad2361117f0e3fb91b.patch | git apply
   # Deal with the case when building in sandbox mode
   if [ -e ../profiles.clj ]; then
       export MAVEN_OPTS="-Dmaven.repo.local=../sandbox-m2"
       echo "{:dev {:local-repo \"../sandbox-m2\"}}" > profiles.clj
   fi
   script/uberjar
   popd
fi

CLJSC_CP=`lein classpath`:clojurescript/target/cljs.jar
java -cp $CLJSC_CP clojure.main script/build.clj
